name: makecut
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Core Packages
  http: ^1.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  youtube_explode_dart: ^2.0.0
  flutter_downloader: ^1.12.0

  # ✅ WORKING FFmpegKit Package (No 404 on iOS)
  ffmpeg_kit_flutter_new: ^1.6.1

  # Sharing & File Handling
  share_plus: ^7.2.2
  open_file: ^3.3.2
  process_run: ^0.13.3+1

  # AdMob
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
